# Generated by Django 3.2.8 on 2021-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='iddetalledocumento',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='iddominio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='idparametro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
