# Generated by Django 3.2.8 on 2021-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20211018_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='log_fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='log_fechamodif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
