# Generated by Django 3.2.8 on 2021-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20211018_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumentoparametro',
            name='log_estado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
