# Generated by Django 3.2.8 on 2021-10-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_detalledocumentoparametro_log_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='iddocumentocontable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
