# Generated by Django 3.2.8 on 2021-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_detalledocumento_iddocumentocontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='log_fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='log_fechamodif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
