# Generated by Django 3.2.8 on 2021-10-19 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_detalledocumento_log_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentidad',
            name='tipo_entidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoentidad',
            name='iddocumentoentidad',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
