# Generated by Django 3.2.8 on 2021-10-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_auto_20211019_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentidad',
            name='iddocumentocontable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
