# Generated by Django 3.2.8 on 2021-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_alter_documentoentidad_iddocumentocontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentidad',
            name='identidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoentidad',
            name='idtipoentidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
