# Generated by Django 3.2.8 on 2021-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_auto_20211019_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentidad',
            name='log_fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentoentidad',
            name='log_fechamodif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
