# Generated by Django 3.2.8 on 2021-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_auto_20211019_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentidad',
            name='log_estado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
