# Generated by Django 3.2.8 on 2021-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_alter_documentoentidad_log_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoparametro',
            name='iddocumentocontable',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoparametro',
            name='idparametro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoparametro',
            name='log_estado',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentoparametro',
            name='log_fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentoparametro',
            name='log_fechamodif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
