# Generated by Django 3.2.8 on 2021-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_auto_20211019_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='control_lotes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='controlar_stock',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='descuento_porcentaje',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='es_de_lista',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='es_favorito',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='id_moneda',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='id_tipo_afectacion_igv',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='id_tipo_precio_venta_unitario',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='tiene_impuesto_bolsa',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalledocumento',
            name='tipo_item',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
