# Generated by Django 3.2.8 on 2021-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_auto_20211019_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='idmsorigen',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
