"""
Django settings for Proxy project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
#import environ
from pathlib import Path
from django.conf.urls import url
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.urls import reverse_lazy
# environ settings
#env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = env('SECRET_KEY')
SECRET_KEY = 'django-insecure-&yvshi!*$mg$nsiq(s9=w@i%n@&g(ir3$b)5sp1)83l5vs^b7l'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = env('DEBUG', default=False)
DEBUG = True

#ALLOWED_HOSTS = tuple(env.list('ALLOWED_HOSTS', default=[]))
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'drf_spectacular',
    'controllers.FacturacionController.apps.FacturacioncontrollerConfig',
    'controllers.LogisticaController.apps.LogisticaControllerConfig',
    'controllers.PlanillasController.apps.PlanillasControllerConfig',
    'controllers.FacturacionControllerCMD.apps.FacturacioncontrollercmdConfig',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'repositorio.ERPQueryEntities',
    'repositorio.ERPProxyEntities.contabilidad',
    'drf_spectacular_sidecar',  # required for Django collectstatic discovery
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOWS_ALL = True
CORS_ORIGIN_CREDENTIAS = True

ROOT_URLCONF = 'Proxy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Proxy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'proxydb.db'),
    },
    'erpquery': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SRERPQry',
        'USER': 'usuariotexao',
        'PASSWORD': '12345',
        'HOST': 'desarrollo.sreasons.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0',
        },
    },
    'srcontabilidad': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SRContabilidad',
        'USER': 'usuariotexao',
        'PASSWORD': '12345',
        'HOST': 'desarrollo.sreasons.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0',
        },
    },
    'srlogistica': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SRLogistica',
        'USER': 'usuariotexao',
        'PASSWORD': '12345',
        'HOST': 'desarrollo.sreasons.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0',
        },
    },
    'srfinanzas': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SRFinanzas',
        'USER': 'usuariotexao',
        'PASSWORD': '12345',
        'HOST': 'desarrollo.sreasons.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0',
        },
    },
    'srcontenidos': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SRFinanzas',
        'USER': 'usuariotexao',
        'PASSWORD': '12345',
        'HOST': 'desarrollo.sreasons.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'SQL Server Native Client 11.0',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
URL_MSFACTURACIONQRY = 'http://desarrollo.sreasons.com/MSFacturacionQry/api/v1/'
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
ALLOWED_HOSTS = ["*"]
SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    # OTHER SETTINGS
}
